-- Copyright (C) 2018  Intel Corporation. All rights reserved.
-- Your use of Intel Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Intel Program License 
-- Subscription Agreement, the Intel Quartus Prime License Agreement,
-- the Intel FPGA IP License Agreement, or other applicable license
-- agreement, including, without limitation, that your use is for
-- the sole purpose of programming logic devices manufactured by
-- Intel and sold by Intel or its authorized distributors.  Please
-- refer to the applicable agreement for further details.

-- Generated by Quartus Prime Version 18.1.0 Build 625 09/12/2018 SJ Lite Edition
-- Created on Mon Jun 15 16:28:45 2026

LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY controller IS
    PORT (
        clock : IN STD_LOGIC;
        reset : IN STD_LOGIC := '0';
        start : IN STD_LOGIC := '0';
        done : IN STD_LOGIC := '0';
        processing : OUT STD_LOGIC;
        pronto : OUT STD_LOGIC
    );
END controller;

ARCHITECTURE BEHAVIOR OF controller IS
    TYPE type_fstate IS (IDLE,STATE_PROCESSING,CLASSIFY,FINISHED);
    SIGNAL fstate : type_fstate;
    SIGNAL reg_fstate : type_fstate;
BEGIN
    PROCESS (clock,reg_fstate)
    BEGIN
        IF (clock='1' AND clock'event) THEN
            fstate <= reg_fstate;
        END IF;
    END PROCESS;

    PROCESS (fstate,reset,start,done)
    BEGIN
        IF (reset='1') THEN
            reg_fstate <= IDLE;
            processing <= '0';
            pronto <= '0';
        ELSE
            processing <= '0';
            pronto <= '0';
            CASE fstate IS
                WHEN IDLE =>
                    IF (NOT((start = '1'))) THEN
                        reg_fstate <= IDLE;
                    ELSIF ((start = '1')) THEN
                        reg_fstate <= STATE_PROCESSING;
                    ELSE
                        reg_fstate <= IDLE;
                    END IF;

                    pronto <= '0';

                    processing <= '0';
                WHEN STATE_PROCESSING =>
                    IF ((done = '1')) THEN
                        reg_fstate <= CLASSIFY;
                    ELSIF (NOT((done = '1'))) THEN
                        reg_fstate <= STATE_PROCESSING;
                    ELSE
                        reg_fstate <= STATE_PROCESSING;
                    END IF;

                    pronto <= '0';

                    processing <= '1';
                WHEN CLASSIFY =>
                    reg_fstate <= FINISHED;

                    pronto <= '0';

                    processing <= '0';
                WHEN FINISHED =>
                    IF (NOT((start = '1'))) THEN
                        reg_fstate <= IDLE;
                    ELSIF ((start = '1')) THEN
                        reg_fstate <= FINISHED;
                    ELSE
                        reg_fstate <= FINISHED;
                    END IF;

                    pronto <= '1';

                    processing <= '0';
                WHEN OTHERS => 
                    processing <= 'X';
                    pronto <= 'X';
                    report "Reach undefined state";
            END CASE;
        END IF;
    END PROCESS;
END BEHAVIOR;
